# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - tweet-text-splitter

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup-infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Check Resource Group Existence
        id: check-rg
        run: |
          EXISTS=$(az group exists --name "testRG")
          echo "RG_EXISTS=$EXISTS" >> $GITHUB_ENV

      - name: Delete Resource Group if Exists
        if: env.RG_EXISTS == 'true'
        run: |
          az group delete --name "testRG" --yes

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  build:
    runs-on: ubuntu-latest
    needs: setup-infrastructure

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Retrieve Azure Web App Publish Profile
        id: getpublishprofile
        run: |
          PUBLISH_PROFILE=$(az webapp deployment list-publishing-profiles --name "tweet-text-splitter" --resource-group "testRG" --xml)
          echo "PUBLISH_PROFILE<<EOF" >> $GITHUB_ENV
          echo "$PUBLISH_PROFILE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
  
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "tweet-text-splitter"
          slot-name: "Production"
          package: .
          publish-profile: ${{ env.PUBLISH_PROFILE }}